/**
 * Turns a scrape in data/bible/ into the two things the app actually ships.
 *
 * The scrape is 190 MB, 162 of it the scraper's own HTML request cache,
 * and it is gitignored — publisher-copyrighted text we do not want in git by
 * accident. What the app needs out of it is far smaller:
 *
 *   public/bible/<VERSION>/<Book>.json   one file per book, minified, fetched
 *                                        on demand: 2-89 KB gzipped, 35 KB for
 *                                        a gospel
 *   src/data/bibleBooks.js               the 66-book table, generated, so a
 *                                        reference can be typed and validated
 *                                        with no network at all
 *
 * Re-run after scraping a new translation:  node scripts/sync-bible.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const VERSION = process.argv[2] || 'MBBTAG'

const src = join(root, 'data', 'bible', VERSION)
const out = join(root, 'public', 'bible', VERSION)

if (!existsSync(src)) {
  console.error(`No scrape at data/bible/${VERSION}. Run scripts/scrape_bible.py first.`)
  process.exit(1)
}

const index = JSON.parse(readFileSync(join(src, 'index.json'), 'utf-8'))

// Canonical order comes from the index; the filename is what the client will
// fetch, so the two have to be matched up here rather than guessed at runtime.
const slugOf = (book) => book.replace(/ /g, '-')

if (existsSync(out)) rmSync(out, { recursive: true })
mkdirSync(out, { recursive: true })

let bytes = 0
const books = index.books.map(({ book, testament, chapters, verses }) => {
  const slug = slugOf(book)
  const data = JSON.parse(readFileSync(join(src, 'books', `${slug}.json`), 'utf-8'))

  // Only the verses travel. Dropping the scrape's provenance fields — source
  // URL, timestamp, the counts already in the index — is most of the saving,
  // and minifying is the rest.
  const payload = JSON.stringify({
    version: data.version,
    book: data.book,
    book_localized: data.book_localized,
    chapters: data.chapters.map((c) => ({
      chapter: c.chapter,
      verses: c.verses.map((v) => ({ verse: v.verse, text: v.text })),
    })),
  })
  writeFileSync(join(out, `${slug}.json`), payload)
  bytes += payload.length

  return {
    slug,
    en: book,
    tl: data.book_localized || book,
    testament,
    chapters,
    verses,
  }
})

// A per-version manifest, so the app can tell which translations are installed
// without probing for files.
writeFileSync(
  join(out, 'index.json'),
  JSON.stringify({ version: index.version, book_count: books.length, verse_count: index.verse_count, books })
)

const table = `/**
 * The 66 books, in canonical order — GENERATED by scripts/sync-bible.mjs.
 * Do not edit by hand; re-run the script instead.
 *
 * This is in the bundle rather than fetched so that typing a reference, and
 * being told it is wrong, needs no network. Only the verses are fetched.
 *
 *   slug       the filename under public/bible/<version>/
 *   en         the name the scrape uses
 *   tl         the name this translation prints, e.g. "Mga Awit" for Psalms
 *   chapters   how many, so "Genesis 51" can be refused before anyone stands
 *              up in front of a congregation with it
 */
export const BIBLE_VERSION = ${JSON.stringify(index.version)}

export const BIBLE_BOOKS = ${JSON.stringify(books, null, 2)}
`
writeFileSync(join(root, 'src', 'data', 'bibleBooks.js'), table)

console.log(
  `${VERSION}: ${books.length} books, ${index.verse_count} verses -> public/bible/${VERSION}/ ` +
    `(${(bytes / 1024 / 1024).toFixed(1)} MB minified)`
)
console.log('Wrote src/data/bibleBooks.js')
